import { themeQuartz } from "ag-grid-community";

export const accountGridTheme = themeQuartz.withParams({
  accentColor: "#0f2744",
  backgroundColor: "#ffffff",
  foregroundColor: "#111827",
  borderColor: "rgba(15, 39, 68, 0.1)",
  borderRadius: 8,
  browserColorScheme: "light",
  chromeBackgroundColor: "#f8fafc",
  fontFamily: ["var(--font-geist-sans)", "system-ui", "sans-serif"],
  fontSize: 13,
  headerBackgroundColor: "#0f2744",
  headerTextColor: "#f8fafc",
  headerFontSize: 12,
  headerFontWeight: 600,
  headerHeight: 48,
  headerVerticalPaddingScale: 1.1,
  oddRowBackgroundColor: "#f9fafb",
  rowHoverColor: "rgba(15, 39, 68, 0.06)",
  selectedRowBackgroundColor: "rgba(15, 39, 68, 0.1)",
  rangeSelectionBackgroundColor: "rgba(15, 39, 68, 0.12)",
  cellHorizontalPadding: 14,
  spacing: 6,
  wrapperBorderRadius: 16,
  wrapperBorder: true,
  rowVerticalPaddingScale: 1.15,
  inputBorder: { color: "rgba(15, 39, 68, 0.18)", width: 1 },
  inputBackgroundColor: "#ffffff",
  inputFocusBorder: { color: "#0f2744", width: 2 },
  focusShadow: { color: "rgba(15, 39, 68, 0.15)", radius: 4, spread: 0 },
  checkboxCheckedBackgroundColor: "#0f2744",
  checkboxCheckedBorderColor: "#0f2744",
  checkboxUncheckedBorderColor: "rgba(15, 39, 68, 0.35)",
  menuBackgroundColor: "#ffffff",
  menuBorder: { color: "rgba(15, 39, 68, 0.12)", width: 1 },
  dropdownShadow: {
    color: "rgba(15, 39, 68, 0.12)",
    radius: 16,
    spread: 0,
    offsetX: 0,
    offsetY: 8,
  },
  cardShadow: {
    color: "rgba(15, 39, 68, 0.1)",
    radius: 12,
    spread: 0,
    offsetX: 0,
    offsetY: 4,
  },
});
