// <auto-generated />
using System;
using CLS.Budget.Infrastructure.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CLS.Budget.EfCore.Migrations
{
    [DbContext(typeof(BudgetDbContext))]
    [Migration("20260702135800_AddTransactionImportIncomeSource")]
    partial class AddTransactionImportIncomeSource
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CLS.Budget.Domain.Entities.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AccountId"));

                    b.Property<int>("AccountCategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AccountOpenDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool?>("IsCreditCard")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPaidOff")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Limit")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MonthlyPayment")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("PaidOffDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Password")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("PaymentDay")
                        .HasColumnType("integer");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Username")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("AccountId");

                    b.HasIndex("Number");

                    b.HasIndex("TenantId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.AccountCategory", b =>
                {
                    b.Property<int>("AccountCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AccountCategoryId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("AccountCategoryId");

                    b.ToTable("AccountCategories");

                    b.HasData(
                        new
                        {
                            AccountCategoryId = 1,
                            Description = "Revolving credit accounts",
                            Name = "Credit Card"
                        },
                        new
                        {
                            AccountCategoryId = 2,
                            Description = "Installment loans",
                            Name = "Loan"
                        },
                        new
                        {
                            AccountCategoryId = 3,
                            Description = "Home mortgage accounts",
                            Name = "Mortgage"
                        },
                        new
                        {
                            AccountCategoryId = 4,
                            Description = "Utility and service bills",
                            Name = "Utility"
                        },
                        new
                        {
                            AccountCategoryId = 5,
                            Description = "Recurring subscriptions",
                            Name = "Subscription"
                        },
                        new
                        {
                            AccountCategoryId = 6,
                            Description = "Savings accounts",
                            Name = "Savings"
                        },
                        new
                        {
                            AccountCategoryId = 7,
                            Description = "Checking accounts",
                            Name = "Checking"
                        });
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique();

                    b.ToTable("AppUser", (string)null);
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.BudgetIncome", b =>
                {
                    b.Property<int>("BudgetIncomeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BudgetIncomeId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("BudgetId")
                        .HasColumnType("integer");

                    b.Property<int>("IncomeSourceId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("ReceivedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("BudgetIncomeId");

                    b.HasIndex("IncomeSourceId");

                    b.HasIndex("TenantId");

                    b.HasIndex("BudgetId", "IncomeSourceId", "ReceivedDate");

                    b.ToTable("BudgetIncome", (string)null);
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.BudgetModel", b =>
                {
                    b.Property<int>("BudgetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BudgetId"));

                    b.Property<string>("AccountIds")
                        .HasColumnType("text");

                    b.Property<int>("BudgetTemplateId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndPeriod")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int?>("PayScheduleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartPeriod")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("BudgetId");

                    b.HasIndex("BudgetTemplateId");

                    b.HasIndex("PayScheduleId");

                    b.HasIndex("TenantId");

                    b.ToTable("Budget", (string)null);
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.BudgetPayment", b =>
                {
                    b.Property<int>("BudgetPaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BudgetPaymentId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("BudgetId")
                        .HasColumnType("integer");

                    b.Property<int>("BudgetPaymentStatusId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ClearedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("IncomeSourceId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCleared")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PaymentMade")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("PaymentSourceId")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("BudgetPaymentId");

                    b.HasIndex("AccountId");

                    b.HasIndex("BudgetPaymentStatusId");

                    b.HasIndex("IncomeSourceId");

                    b.HasIndex("PaymentSourceId");

                    b.HasIndex("TenantId");

                    b.HasIndex("BudgetId", "AccountId", "PaymentDate");

                    b.ToTable("BudgetPayments", (string)null);
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.BudgetPaymentStatus", b =>
                {
                    b.Property<int>("BudgetPaymentStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BudgetPaymentStatusId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("BudgetPaymentStatusId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("BudgetPaymentStatus", (string)null);

                    b.HasData(
                        new
                        {
                            BudgetPaymentStatusId = 1,
                            Description = "Not yet paid",
                            Name = "Pending"
                        },
                        new
                        {
                            BudgetPaymentStatusId = 2,
                            Description = "Scheduled for payment",
                            Name = "Scheduled"
                        },
                        new
                        {
                            BudgetPaymentStatusId = 3,
                            Description = "Payment completed",
                            Name = "Paid"
                        },
                        new
                        {
                            BudgetPaymentStatusId = 4,
                            Description = "Payment attempt failed",
                            Name = "Failed"
                        },
                        new
                        {
                            BudgetPaymentStatusId = 5,
                            Description = "Past due and not paid",
                            Name = "Overdue"
                        },
                        new
                        {
                            BudgetPaymentStatusId = 6,
                            Description = "Status not yet chosen",
                            Name = "Unassigned"
                        });
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.BudgetTemplate", b =>
                {
                    b.Property<int>("BudgetTemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BudgetTemplateId"));

                    b.Property<string>("AccountIds")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("BudgetTemplateId");

                    b.ToTable("BudgetTemplates");

                    b.HasData(
                        new
                        {
                            BudgetTemplateId = 1,
                            Description = "Default template for monthly budget planning",
                            Name = "Monthly Household Budget"
                        });
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.CreditCardDetail", b =>
                {
                    b.Property<int>("CreditCardDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CreditCardDetailId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("CashOutInterestRate")
                        .HasColumnType("numeric(8,4)");

                    b.Property<decimal?>("InterestRate")
                        .HasColumnType("numeric(8,4)");

                    b.Property<decimal?>("Limit")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("CreditCardDetailId");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("CreditCardDetail", (string)null);
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.ImportedTransaction", b =>
                {
                    b.Property<int>("ImportedTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ImportedTransactionId"));

                    b.Property<int?>("AccountCategoryId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("BudgetPaymentStatusId")
                        .HasColumnType("integer");

                    b.Property<string>("CategoryRaw")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("IncomeSourceId")
                        .HasColumnType("integer");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("PostingStatusRaw")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TransactionImportId")
                        .HasColumnType("integer");

                    b.HasKey("ImportedTransactionId");

                    b.HasIndex("AccountCategoryId");

                    b.HasIndex("BudgetPaymentStatusId");

                    b.HasIndex("IncomeSourceId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TransactionImportId", "LineNumber");

                    b.ToTable("ImportedTransaction", (string)null);
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.IncomeSource", b =>
                {
                    b.Property<int>("IncomeSourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IncomeSourceId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("IncomeSourceId");

                    b.ToTable("IncomeSource", (string)null);

                    b.HasData(
                        new
                        {
                            IncomeSourceId = 1,
                            IsActive = true,
                            Name = "Job Income"
                        },
                        new
                        {
                            IncomeSourceId = 2,
                            IsActive = true,
                            Name = "Credit Cards"
                        },
                        new
                        {
                            IncomeSourceId = 3,
                            IsActive = true,
                            Name = "Business Income"
                        });
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("PasswordResetTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("PasswordResetTokenId");

                    b.HasIndex("TokenHash");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetToken", (string)null);
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.PayFrequencyType", b =>
                {
                    b.Property<int>("PayFrequencyTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PayFrequencyTypeId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("PayFrequencyTypeId");

                    b.ToTable("PayFrequencyType", (string)null);

                    b.HasData(
                        new
                        {
                            PayFrequencyTypeId = 1,
                            Description = "Paid every 7 days on a fixed weekday",
                            Name = "Weekly"
                        },
                        new
                        {
                            PayFrequencyTypeId = 2,
                            Description = "Paid every 14 days on a fixed weekday",
                            Name = "BiWeekly"
                        },
                        new
                        {
                            PayFrequencyTypeId = 3,
                            Description = "Paid twice per month on fixed calendar days",
                            Name = "SemiMonthly"
                        });
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.PaySchedule", b =>
                {
                    b.Property<int>("PayScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PayScheduleId"));

                    b.Property<DateTime?>("AnchorDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<int>("IncomeSourceId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PayFrequencyTypeId")
                        .HasColumnType("integer");

                    b.Property<int?>("SemiMonthlyDay1")
                        .HasColumnType("integer");

                    b.Property<int?>("SemiMonthlyDay2")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("PayScheduleId");

                    b.HasIndex("IncomeSourceId");

                    b.HasIndex("PayFrequencyTypeId");

                    b.HasIndex("TenantId");

                    b.ToTable("PaySchedule", (string)null);

                    b.HasData(
                        new
                        {
                            PayScheduleId = 1,
                            IncomeSourceId = 1,
                            IsActive = true,
                            IsDefault = true,
                            Name = "Twice monthly (1st & 15th)",
                            PayFrequencyTypeId = 3,
                            SemiMonthlyDay1 = 1,
                            SemiMonthlyDay2 = 15,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.PaymentSource", b =>
                {
                    b.Property<int>("PaymentSourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaymentSourceId"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("PaymentSourceId");

                    b.ToTable("PaymentSource", (string)null);

                    b.HasData(
                        new
                        {
                            PaymentSourceId = 1,
                            Description = "Hudson Valley Credit Union checking",
                            Name = "HVCU"
                        },
                        new
                        {
                            PaymentSourceId = 2,
                            Description = "HVCU credit card used for payments",
                            Name = "HVCU CC"
                        },
                        new
                        {
                            PaymentSourceId = 3,
                            Description = "Alternate / American Express funding account",
                            Name = "AE"
                        });
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("RefreshTokenId");

                    b.HasIndex("TokenHash");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshToken", (string)null);
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("TenantId");

                    b.ToTable("Tenant", (string)null);

                    b.HasData(
                        new
                        {
                            TenantId = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "MonaArthur"
                        });
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.TransactionImport", b =>
                {
                    b.Property<int>("TransactionImportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TransactionImportId"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("IncomeSourceId")
                        .HasColumnType("integer");

                    b.Property<int>("RowCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TransactionImportId");

                    b.HasIndex("IncomeSourceId");

                    b.HasIndex("TenantId");

                    b.ToTable("TransactionImport", (string)null);
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.AppUser", b =>
                {
                    b.HasOne("CLS.Budget.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.BudgetIncome", b =>
                {
                    b.HasOne("CLS.Budget.Domain.Entities.BudgetModel", null)
                        .WithMany()
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CLS.Budget.Domain.Entities.IncomeSource", "IncomeSource")
                        .WithMany()
                        .HasForeignKey("IncomeSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IncomeSource");
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.BudgetModel", b =>
                {
                    b.HasOne("CLS.Budget.Domain.Entities.BudgetTemplate", "BudgetTemplate")
                        .WithMany()
                        .HasForeignKey("BudgetTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CLS.Budget.Domain.Entities.PaySchedule", "PaySchedule")
                        .WithMany()
                        .HasForeignKey("PayScheduleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BudgetTemplate");

                    b.Navigation("PaySchedule");
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.BudgetPayment", b =>
                {
                    b.HasOne("CLS.Budget.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CLS.Budget.Domain.Entities.BudgetModel", null)
                        .WithMany("BudgetPayments")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CLS.Budget.Domain.Entities.BudgetPaymentStatus", "BudgetPaymentStatus")
                        .WithMany()
                        .HasForeignKey("BudgetPaymentStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CLS.Budget.Domain.Entities.IncomeSource", "IncomeSource")
                        .WithMany()
                        .HasForeignKey("IncomeSourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CLS.Budget.Domain.Entities.PaymentSource", "PaymentSource")
                        .WithMany()
                        .HasForeignKey("PaymentSourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Account");

                    b.Navigation("BudgetPaymentStatus");

                    b.Navigation("IncomeSource");

                    b.Navigation("PaymentSource");
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.CreditCardDetail", b =>
                {
                    b.HasOne("CLS.Budget.Domain.Entities.Account", "Account")
                        .WithOne("CreditCardDetail")
                        .HasForeignKey("CLS.Budget.Domain.Entities.CreditCardDetail", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.ImportedTransaction", b =>
                {
                    b.HasOne("CLS.Budget.Domain.Entities.AccountCategory", "AccountCategory")
                        .WithMany()
                        .HasForeignKey("AccountCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CLS.Budget.Domain.Entities.BudgetPaymentStatus", "BudgetPaymentStatus")
                        .WithMany()
                        .HasForeignKey("BudgetPaymentStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CLS.Budget.Domain.Entities.IncomeSource", "IncomeSource")
                        .WithMany()
                        .HasForeignKey("IncomeSourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CLS.Budget.Domain.Entities.TransactionImport", "TransactionImport")
                        .WithMany("Transactions")
                        .HasForeignKey("TransactionImportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountCategory");

                    b.Navigation("BudgetPaymentStatus");

                    b.Navigation("IncomeSource");

                    b.Navigation("TransactionImport");
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("CLS.Budget.Domain.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.PaySchedule", b =>
                {
                    b.HasOne("CLS.Budget.Domain.Entities.IncomeSource", "IncomeSource")
                        .WithMany()
                        .HasForeignKey("IncomeSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CLS.Budget.Domain.Entities.PayFrequencyType", "PayFrequencyType")
                        .WithMany()
                        .HasForeignKey("PayFrequencyTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IncomeSource");

                    b.Navigation("PayFrequencyType");
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("CLS.Budget.Domain.Entities.AppUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.TransactionImport", b =>
                {
                    b.HasOne("CLS.Budget.Domain.Entities.IncomeSource", "IncomeSource")
                        .WithMany()
                        .HasForeignKey("IncomeSourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("IncomeSource");
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.Account", b =>
                {
                    b.Navigation("CreditCardDetail");
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.BudgetModel", b =>
                {
                    b.Navigation("BudgetPayments");
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.TransactionImport", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
