// <auto-generated />
using System;
using CLS.Budget.Infrastructure.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CLS.Budget.EfCore.Migrations
{
    [DbContext(typeof(BudgetDbContext))]
    [Migration("20260522020843_AddBudgetPaymentAmount")]
    partial class AddBudgetPaymentAmount
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CLS.Budget.Domain.Entities.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AccountId"));

                    b.Property<int>("AccountCategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AccountOpenDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool?>("IsCreditCard")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPaidOff")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Limit")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MonthlyPayment")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("PaidOffDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Password")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Username")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("AccountId");

                    b.HasIndex("Number");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.AccountCategory", b =>
                {
                    b.Property<int>("AccountCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AccountCategoryId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("AccountCategoryId");

                    b.ToTable("AccountCategories");

                    b.HasData(
                        new
                        {
                            AccountCategoryId = 1,
                            Description = "Revolving credit accounts",
                            Name = "Credit Card"
                        },
                        new
                        {
                            AccountCategoryId = 2,
                            Description = "Installment loans",
                            Name = "Loan"
                        },
                        new
                        {
                            AccountCategoryId = 3,
                            Description = "Home mortgage accounts",
                            Name = "Mortgage"
                        },
                        new
                        {
                            AccountCategoryId = 4,
                            Description = "Utility and service bills",
                            Name = "Utility"
                        },
                        new
                        {
                            AccountCategoryId = 5,
                            Description = "Recurring subscriptions",
                            Name = "Subscription"
                        },
                        new
                        {
                            AccountCategoryId = 6,
                            Description = "Savings accounts",
                            Name = "Savings"
                        },
                        new
                        {
                            AccountCategoryId = 7,
                            Description = "Checking accounts",
                            Name = "Checking"
                        });
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.BudgetModel", b =>
                {
                    b.Property<int>("BudgetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BudgetId"));

                    b.Property<string>("AccountIds")
                        .HasColumnType("text");

                    b.Property<int>("BudgetTemplateId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndPeriod")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("StartPeriod")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BudgetId");

                    b.HasIndex("BudgetTemplateId");

                    b.ToTable("Budget", (string)null);
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.BudgetPayment", b =>
                {
                    b.Property<int>("BudgetPaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BudgetPaymentId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("BudgetId")
                        .HasColumnType("integer");

                    b.Property<int>("BudgetPaymentStatusId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ClearedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCleared")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PaymentMade")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("PaymentSourceId")
                        .HasColumnType("integer");

                    b.HasKey("BudgetPaymentId");

                    b.HasIndex("AccountId");

                    b.HasIndex("BudgetPaymentStatusId");

                    b.HasIndex("PaymentSourceId");

                    b.HasIndex("BudgetId", "AccountId", "PaymentDate");

                    b.ToTable("BudgetPayments", (string)null);
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.BudgetPaymentStatus", b =>
                {
                    b.Property<int>("BudgetPaymentStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BudgetPaymentStatusId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("BudgetPaymentStatusId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("BudgetPaymentStatus", (string)null);

                    b.HasData(
                        new
                        {
                            BudgetPaymentStatusId = 1,
                            Description = "Not yet paid",
                            Name = "Pending"
                        },
                        new
                        {
                            BudgetPaymentStatusId = 2,
                            Description = "Scheduled for payment",
                            Name = "Scheduled"
                        },
                        new
                        {
                            BudgetPaymentStatusId = 3,
                            Description = "Payment completed",
                            Name = "Paid"
                        },
                        new
                        {
                            BudgetPaymentStatusId = 4,
                            Description = "Payment attempt failed",
                            Name = "Failed"
                        },
                        new
                        {
                            BudgetPaymentStatusId = 5,
                            Description = "Past due and not paid",
                            Name = "Overdue"
                        });
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.BudgetTemplate", b =>
                {
                    b.Property<int>("BudgetTemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BudgetTemplateId"));

                    b.Property<string>("AccountIds")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("BudgetTemplateId");

                    b.ToTable("BudgetTemplates");

                    b.HasData(
                        new
                        {
                            BudgetTemplateId = 1,
                            Description = "Default template for monthly budget planning",
                            Name = "Monthly Household Budget"
                        });
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.CreditCardDetail", b =>
                {
                    b.Property<int>("CreditCardDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CreditCardDetailId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("AnnualFee")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("CreditLimit")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("InterestRate")
                        .HasColumnType("numeric(8,4)");

                    b.Property<decimal?>("LastPaymentAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("LastPaymentBalance")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("LastPaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("MinimumPayment")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("CreditCardDetailId");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("CreditCardDetail", (string)null);
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.PaymentSource", b =>
                {
                    b.Property<int>("PaymentSourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaymentSourceId"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("PaymentSourceId");

                    b.ToTable("PaymentSource", (string)null);
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.BudgetModel", b =>
                {
                    b.HasOne("CLS.Budget.Domain.Entities.BudgetTemplate", "BudgetTemplate")
                        .WithMany()
                        .HasForeignKey("BudgetTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BudgetTemplate");
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.BudgetPayment", b =>
                {
                    b.HasOne("CLS.Budget.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CLS.Budget.Domain.Entities.BudgetModel", null)
                        .WithMany("BudgetPayments")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CLS.Budget.Domain.Entities.BudgetPaymentStatus", "BudgetPaymentStatus")
                        .WithMany()
                        .HasForeignKey("BudgetPaymentStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CLS.Budget.Domain.Entities.PaymentSource", "PaymentSource")
                        .WithMany()
                        .HasForeignKey("PaymentSourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Account");

                    b.Navigation("BudgetPaymentStatus");

                    b.Navigation("PaymentSource");
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.CreditCardDetail", b =>
                {
                    b.HasOne("CLS.Budget.Domain.Entities.Account", "Account")
                        .WithOne("CreditCardDetail")
                        .HasForeignKey("CLS.Budget.Domain.Entities.CreditCardDetail", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.Account", b =>
                {
                    b.Navigation("CreditCardDetail");
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.BudgetModel", b =>
                {
                    b.Navigation("BudgetPayments");
                });
#pragma warning restore 612, 618
        }
    }
}
