// <auto-generated />
using System;
using CLS.Budget.Infrastructure.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CLS.Budget.EfCore.Migrations
{
    [DbContext(typeof(BudgetDbContext))]
    [Migration("20260728184022_AddAccountGraceDay")]
    partial class AddAccountGraceDay
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CLS.Budget.Domain.Entities.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AccountId"));

                    b.Property<int>("AccountCategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AccountOpenDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("AccountSubCategoryId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("GraceDay")
                        .HasColumnType("integer");

                    b.Property<int?>("GracePeriod")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsCreditCard")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPaidOff")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Limit")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MonthlyPayment")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("PaidOffDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Password")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("PaymentDay")
                        .HasColumnType("integer");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Username")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("AccountId");

                    b.HasIndex("AccountCategoryId");

                    b.HasIndex("AccountSubCategoryId");

                    b.HasIndex("Number");

                    b.HasIndex("TenantId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.AccountCategory", b =>
                {
                    b.Property<int>("AccountCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AccountCategoryId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("AccountCategoryId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Name");

                    b.ToTable("AccountCategories", (string)null);

                    b.HasData(
                        new
                        {
                            AccountCategoryId = 1,
                            Description = "Revolving credit accounts",
                            IsSystem = true,
                            Name = "Credit Card"
                        },
                        new
                        {
                            AccountCategoryId = 2,
                            Description = "Installment loans",
                            IsSystem = true,
                            Name = "Loan"
                        },
                        new
                        {
                            AccountCategoryId = 3,
                            Description = "Home mortgage accounts",
                            IsSystem = true,
                            Name = "Mortgage"
                        },
                        new
                        {
                            AccountCategoryId = 4,
                            Description = "Utility and service bills",
                            IsSystem = true,
                            Name = "Utility"
                        },
                        new
                        {
                            AccountCategoryId = 5,
                            Description = "Recurring subscriptions",
                            IsSystem = true,
                            Name = "Subscription"
                        },
                        new
                        {
                            AccountCategoryId = 6,
                            Description = "Savings accounts",
                            IsSystem = true,
                            Name = "Savings"
                        },
                        new
                        {
                            AccountCategoryId = 7,
                            Description = "Checking accounts",
                            IsSystem = true,
                            Name = "Checking"
                        });
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.AccountSubCategory", b =>
                {
                    b.Property<int>("AccountSubCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AccountSubCategoryId"));

                    b.Property<int>("AccountCategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("AccountSubCategoryId");

                    b.HasIndex("AccountCategoryId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "AccountCategoryId", "Name");

                    b.ToTable("AccountSubCategory", (string)null);
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.ActivePayoffPlan", b =>
                {
                    b.Property<int>("ActivePayoffPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ActivePayoffPlanId"));

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentVersionNumber")
                        .HasColumnType("integer");

                    b.Property<bool>("EnableCashAdvanceBalanceMoves")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("EndedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ExtraMonthlyPayment")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Goal")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("LoanAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("LoanAnnualPercentageRate")
                        .HasColumnType("numeric(8,4)");

                    b.Property<string>("LoanApplyCreditCardIdsJson")
                        .HasColumnType("text");

                    b.Property<string>("LoanApplyStrategy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("LoanFixedMonthlyPayment")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("LoanInterestOnlyMonths")
                        .HasColumnType("integer");

                    b.Property<int?>("LoanTermMonths")
                        .HasColumnType("integer");

                    b.Property<string>("LoanType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("PayOverLimitFirst")
                        .HasColumnType("boolean");

                    b.Property<string>("PostUtilizationStrategy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PromotionalTransfersJson")
                        .HasColumnType("text");

                    b.Property<int?>("SourceSavedPayoffPlanId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("StartingDebt")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("TargetUtilizationPercent")
                        .HasColumnType("numeric(5,2)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalMonthlyDebtPayment")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ActivePayoffPlanId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("ActivePayoffPlan", (string)null);
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique();

                    b.ToTable("AppUser", (string)null);
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.BudgetIncome", b =>
                {
                    b.Property<int>("BudgetIncomeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BudgetIncomeId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("BudgetId")
                        .HasColumnType("integer");

                    b.Property<int>("IncomeSourceId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("ReceivedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("BudgetIncomeId");

                    b.HasIndex("IncomeSourceId");

                    b.HasIndex("TenantId");

                    b.HasIndex("BudgetId", "IncomeSourceId", "ReceivedDate");

                    b.ToTable("BudgetIncome", (string)null);
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.BudgetModel", b =>
                {
                    b.Property<int>("BudgetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BudgetId"));

                    b.Property<string>("AccountIds")
                        .HasColumnType("text");

                    b.Property<int>("BudgetTemplateId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndPeriod")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int?>("PayScheduleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartPeriod")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("BudgetId");

                    b.HasIndex("BudgetTemplateId");

                    b.HasIndex("PayScheduleId");

                    b.HasIndex("TenantId");

                    b.ToTable("Budget", (string)null);
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.BudgetPayment", b =>
                {
                    b.Property<int>("BudgetPaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BudgetPaymentId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("BudgetId")
                        .HasColumnType("integer");

                    b.Property<int>("BudgetPaymentStatusId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ClearedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("IncomeSourceId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCleared")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PaymentMade")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("PaymentSourceId")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("BudgetPaymentId");

                    b.HasIndex("AccountId");

                    b.HasIndex("BudgetPaymentStatusId");

                    b.HasIndex("IncomeSourceId");

                    b.HasIndex("PaymentSourceId");

                    b.HasIndex("TenantId");

                    b.HasIndex("BudgetId", "AccountId", "PaymentDate");

                    b.ToTable("BudgetPayments", (string)null);
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.BudgetPaymentStatus", b =>
                {
                    b.Property<int>("BudgetPaymentStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BudgetPaymentStatusId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("BudgetPaymentStatusId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("BudgetPaymentStatus", (string)null);

                    b.HasData(
                        new
                        {
                            BudgetPaymentStatusId = 1,
                            Description = "Not yet paid",
                            Name = "Pending"
                        },
                        new
                        {
                            BudgetPaymentStatusId = 2,
                            Description = "Scheduled for payment",
                            Name = "Scheduled"
                        },
                        new
                        {
                            BudgetPaymentStatusId = 3,
                            Description = "Payment completed",
                            Name = "Paid"
                        },
                        new
                        {
                            BudgetPaymentStatusId = 4,
                            Description = "Payment attempt failed",
                            Name = "Failed"
                        },
                        new
                        {
                            BudgetPaymentStatusId = 5,
                            Description = "Past due and not paid",
                            Name = "Overdue"
                        },
                        new
                        {
                            BudgetPaymentStatusId = 6,
                            Description = "Status not yet chosen",
                            Name = "Unassigned"
                        },
                        new
                        {
                            BudgetPaymentStatusId = 7,
                            Description = "Scheduled for online payment",
                            Name = "Scheduled Online"
                        });
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.BudgetTemplate", b =>
                {
                    b.Property<int>("BudgetTemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BudgetTemplateId"));

                    b.Property<string>("AccountIds")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("BudgetTemplateId");

                    b.ToTable("BudgetTemplates");

                    b.HasData(
                        new
                        {
                            BudgetTemplateId = 1,
                            Description = "Default template for monthly budget planning",
                            Name = "Monthly Household Budget"
                        });
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.CreditCardDetail", b =>
                {
                    b.Property<int>("CreditCardDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CreditCardDetailId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("CashAdvanceFeePercentage")
                        .HasColumnType("numeric(8,4)");

                    b.Property<decimal?>("CashOutInterestRate")
                        .HasColumnType("numeric(8,4)");

                    b.Property<bool>("IncludeInPayoffAnalysis")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("InterestRate")
                        .HasColumnType("numeric(8,4)");

                    b.Property<decimal?>("Limit")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("MinimumPaymentFloor")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("MinimumPaymentPercentage")
                        .HasColumnType("numeric(8,4)");

                    b.Property<decimal?>("PromotionalAnnualPercentageRate")
                        .HasColumnType("numeric(8,4)");

                    b.Property<DateTime?>("PromotionalRateExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("CreditCardDetailId");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("CreditCardDetail", (string)null);
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.ForecastMonthlySnapshot", b =>
                {
                    b.Property<int>("ForecastMonthlySnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ForecastMonthlySnapshotId"));

                    b.Property<decimal>("AvailableCash")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("CardsPaidOffThisMonth")
                        .HasColumnType("integer");

                    b.Property<decimal>("CumulativeInterest")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("EndingDebt")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ForecastScenarioId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Interest")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateOnly>("Month")
                        .HasColumnType("date");

                    b.Property<int>("MonthIndex")
                        .HasColumnType("integer");

                    b.Property<decimal>("NewCharges")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("OverallUtilizationPercentage")
                        .HasColumnType("numeric(8,4)");

                    b.Property<decimal>("Payments")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("StartingDebt")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalCreditLimit")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("ForecastMonthlySnapshotId");

                    b.HasIndex("TenantId");

                    b.HasIndex("ForecastScenarioId", "MonthIndex");

                    b.ToTable("ForecastMonthlySnapshot", (string)null);
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.ForecastScenario", b =>
                {
                    b.Property<int>("ForecastScenarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ForecastScenarioId"));

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("EstimatedDebtFreeDate")
                        .HasColumnType("date");

                    b.Property<int>("ForecastMonths")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MonthlyExpenses")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("MonthlyNetIncome")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("PayOverLimitFirst")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<decimal>("StartingDebt")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("TargetUtilizationPercent")
                        .HasColumnType("numeric(5,2)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalInterestPaid")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotalMonthlyDebtPayment")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("ForecastScenarioId");

                    b.HasIndex("TenantId");

                    b.ToTable("ForecastScenario", (string)null);
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.ForecastScenarioCreditCard", b =>
                {
                    b.Property<int>("ForecastScenarioCreditCardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ForecastScenarioCreditCardId"));

                    b.Property<decimal>("AnnualPercentageRate")
                        .HasColumnType("numeric(8,4)");

                    b.Property<int>("CreditCardId")
                        .HasColumnType("integer");

                    b.Property<decimal>("CreditLimit")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ForecastScenarioId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("StartingBalance")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("ForecastScenarioCreditCardId");

                    b.HasIndex("ForecastScenarioId");

                    b.HasIndex("TenantId");

                    b.ToTable("ForecastScenarioCreditCard", (string)null);
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.ImportedTransaction", b =>
                {
                    b.Property<int>("ImportedTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ImportedTransactionId"));

                    b.Property<int?>("AccountCategoryId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("BudgetPaymentStatusId")
                        .HasColumnType("integer");

                    b.Property<string>("CategoryRaw")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("IncomeSourceId")
                        .HasColumnType("integer");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("PostingStatusRaw")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TransactionImportId")
                        .HasColumnType("integer");

                    b.HasKey("ImportedTransactionId");

                    b.HasIndex("AccountCategoryId");

                    b.HasIndex("BudgetPaymentStatusId");

                    b.HasIndex("IncomeSourceId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TransactionImportId", "LineNumber");

                    b.ToTable("ImportedTransaction", (string)null);
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.IncomeSource", b =>
                {
                    b.Property<int>("IncomeSourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IncomeSourceId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("IncomeSourceId");

                    b.ToTable("IncomeSource", (string)null);

                    b.HasData(
                        new
                        {
                            IncomeSourceId = 1,
                            IsActive = true,
                            Name = "Job Income"
                        },
                        new
                        {
                            IncomeSourceId = 2,
                            IsActive = true,
                            Name = "Credit Cards"
                        },
                        new
                        {
                            IncomeSourceId = 3,
                            IsActive = true,
                            Name = "Business Income"
                        });
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("PasswordResetTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("PasswordResetTokenId");

                    b.HasIndex("TokenHash");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetToken", (string)null);
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.PayFrequencyType", b =>
                {
                    b.Property<int>("PayFrequencyTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PayFrequencyTypeId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("PayFrequencyTypeId");

                    b.ToTable("PayFrequencyType", (string)null);

                    b.HasData(
                        new
                        {
                            PayFrequencyTypeId = 1,
                            Description = "Paid every 7 days on a fixed weekday",
                            Name = "Weekly"
                        },
                        new
                        {
                            PayFrequencyTypeId = 2,
                            Description = "Paid every 14 days on a fixed weekday",
                            Name = "BiWeekly"
                        },
                        new
                        {
                            PayFrequencyTypeId = 3,
                            Description = "Paid twice per month on fixed calendar days",
                            Name = "SemiMonthly"
                        });
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.PaySchedule", b =>
                {
                    b.Property<int>("PayScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PayScheduleId"));

                    b.Property<DateTime?>("AnchorDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<int>("IncomeSourceId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PayFrequencyTypeId")
                        .HasColumnType("integer");

                    b.Property<int?>("SemiMonthlyDay1")
                        .HasColumnType("integer");

                    b.Property<int?>("SemiMonthlyDay2")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("PayScheduleId");

                    b.HasIndex("IncomeSourceId");

                    b.HasIndex("PayFrequencyTypeId");

                    b.HasIndex("TenantId");

                    b.ToTable("PaySchedule", (string)null);

                    b.HasData(
                        new
                        {
                            PayScheduleId = 1,
                            IncomeSourceId = 1,
                            IsActive = true,
                            IsDefault = true,
                            Name = "Twice monthly (1st & 15th)",
                            PayFrequencyTypeId = 3,
                            SemiMonthlyDay1 = 1,
                            SemiMonthlyDay2 = 15,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.PaymentSource", b =>
                {
                    b.Property<int>("PaymentSourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaymentSourceId"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("PaymentSourceId");

                    b.ToTable("PaymentSource", (string)null);

                    b.HasData(
                        new
                        {
                            PaymentSourceId = 1,
                            Description = "Hudson Valley Credit Union checking",
                            Name = "HVCU"
                        },
                        new
                        {
                            PaymentSourceId = 2,
                            Description = "HVCU credit card used for payments",
                            Name = "HVCU CC"
                        },
                        new
                        {
                            PaymentSourceId = 3,
                            Description = "Alternate / American Express funding account",
                            Name = "AE"
                        });
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.PayoffPlanEvent", b =>
                {
                    b.Property<int>("PayoffPlanEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PayoffPlanEventId"));

                    b.Property<int>("ActivePayoffPlanId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("PayoffPlanEventId");

                    b.HasIndex("TenantId");

                    b.HasIndex("ActivePayoffPlanId", "CreatedOnUtc");

                    b.ToTable("PayoffPlanEvent", (string)null);
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.PayoffPlanPayment", b =>
                {
                    b.Property<int>("PayoffPlanPaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PayoffPlanPaymentId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<int>("ActivePayoffPlanId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsVoided")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("date");

                    b.Property<int>("PayoffPlanVersionId")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("VoidedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PayoffPlanPaymentId");

                    b.HasIndex("AccountId");

                    b.HasIndex("PayoffPlanVersionId");

                    b.HasIndex("TenantId");

                    b.HasIndex("ActivePayoffPlanId", "PaymentDate");

                    b.ToTable("PayoffPlanPayment", (string)null);
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.PayoffPlanVersion", b =>
                {
                    b.Property<int>("PayoffPlanVersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PayoffPlanVersionId"));

                    b.Property<int>("ActivePayoffPlanId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EnableCashAdvanceBalanceMoves")
                        .HasColumnType("boolean");

                    b.Property<decimal>("ExtraMonthlyPayment")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Goal")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("LoanAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("LoanAnnualPercentageRate")
                        .HasColumnType("numeric(8,4)");

                    b.Property<string>("LoanApplyCreditCardIdsJson")
                        .HasColumnType("text");

                    b.Property<string>("LoanApplyStrategy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("LoanFixedMonthlyPayment")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("LoanInterestOnlyMonths")
                        .HasColumnType("integer");

                    b.Property<int?>("LoanTermMonths")
                        .HasColumnType("integer");

                    b.Property<string>("LoanType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("PayOverLimitFirst")
                        .HasColumnType("boolean");

                    b.Property<string>("PostUtilizationStrategy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ProjectedMonthsToPayoff")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("ProjectedPayoffDate")
                        .HasColumnType("date");

                    b.Property<decimal>("ProjectedTotalInterest")
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("ProjectionIsValid")
                        .HasColumnType("boolean");

                    b.Property<string>("PromotionalTransfersJson")
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("SnapshotDebt")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("TargetUtilizationPercent")
                        .HasColumnType("numeric(5,2)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalMonthlyDebtPayment")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("PayoffPlanVersionId");

                    b.HasIndex("TenantId");

                    b.HasIndex("ActivePayoffPlanId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("PayoffPlanVersion", (string)null);
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("RefreshTokenId");

                    b.HasIndex("TokenHash");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshToken", (string)null);
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.SavedPayoffPlan", b =>
                {
                    b.Property<int>("SavedPayoffPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SavedPayoffPlanId"));

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EnableCashAdvanceBalanceMoves")
                        .HasColumnType("boolean");

                    b.Property<decimal>("ExtraMonthlyPayment")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Goal")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("LoanAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("LoanAnnualPercentageRate")
                        .HasColumnType("numeric(8,4)");

                    b.Property<string>("LoanApplyCreditCardIdsJson")
                        .HasColumnType("text");

                    b.Property<string>("LoanApplyStrategy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("LoanFixedMonthlyPayment")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("LoanInterestOnlyMonths")
                        .HasColumnType("integer");

                    b.Property<int?>("LoanTermMonths")
                        .HasColumnType("integer");

                    b.Property<string>("LoanType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("PayOverLimitFirst")
                        .HasColumnType("boolean");

                    b.Property<string>("PostUtilizationStrategy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PromotionalTransfersJson")
                        .HasColumnType("text");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("TargetUtilizationPercent")
                        .HasColumnType("numeric(5,2)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalMonthlyDebtPayment")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SavedPayoffPlanId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "CreatedOnUtc");

                    b.ToTable("SavedPayoffPlan", (string)null);
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("TenantId");

                    b.ToTable("Tenant", (string)null);

                    b.HasData(
                        new
                        {
                            TenantId = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "MonaArthur"
                        });
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.TransactionImport", b =>
                {
                    b.Property<int>("TransactionImportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TransactionImportId"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("IncomeSourceId")
                        .HasColumnType("integer");

                    b.Property<int>("RowCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TransactionImportId");

                    b.HasIndex("IncomeSourceId");

                    b.HasIndex("TenantId");

                    b.ToTable("TransactionImport", (string)null);
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.Account", b =>
                {
                    b.HasOne("CLS.Budget.Domain.Entities.AccountCategory", "AccountCategory")
                        .WithMany()
                        .HasForeignKey("AccountCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CLS.Budget.Domain.Entities.AccountSubCategory", "AccountSubCategory")
                        .WithMany()
                        .HasForeignKey("AccountSubCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AccountCategory");

                    b.Navigation("AccountSubCategory");
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.AccountSubCategory", b =>
                {
                    b.HasOne("CLS.Budget.Domain.Entities.AccountCategory", "AccountCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("AccountCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AccountCategory");
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.AppUser", b =>
                {
                    b.HasOne("CLS.Budget.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.BudgetIncome", b =>
                {
                    b.HasOne("CLS.Budget.Domain.Entities.BudgetModel", null)
                        .WithMany()
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CLS.Budget.Domain.Entities.IncomeSource", "IncomeSource")
                        .WithMany()
                        .HasForeignKey("IncomeSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IncomeSource");
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.BudgetModel", b =>
                {
                    b.HasOne("CLS.Budget.Domain.Entities.BudgetTemplate", "BudgetTemplate")
                        .WithMany()
                        .HasForeignKey("BudgetTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CLS.Budget.Domain.Entities.PaySchedule", "PaySchedule")
                        .WithMany()
                        .HasForeignKey("PayScheduleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BudgetTemplate");

                    b.Navigation("PaySchedule");
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.BudgetPayment", b =>
                {
                    b.HasOne("CLS.Budget.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CLS.Budget.Domain.Entities.BudgetModel", null)
                        .WithMany("BudgetPayments")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CLS.Budget.Domain.Entities.BudgetPaymentStatus", "BudgetPaymentStatus")
                        .WithMany()
                        .HasForeignKey("BudgetPaymentStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CLS.Budget.Domain.Entities.IncomeSource", "IncomeSource")
                        .WithMany()
                        .HasForeignKey("IncomeSourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CLS.Budget.Domain.Entities.PaymentSource", "PaymentSource")
                        .WithMany()
                        .HasForeignKey("PaymentSourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Account");

                    b.Navigation("BudgetPaymentStatus");

                    b.Navigation("IncomeSource");

                    b.Navigation("PaymentSource");
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.CreditCardDetail", b =>
                {
                    b.HasOne("CLS.Budget.Domain.Entities.Account", "Account")
                        .WithOne("CreditCardDetail")
                        .HasForeignKey("CLS.Budget.Domain.Entities.CreditCardDetail", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.ForecastMonthlySnapshot", b =>
                {
                    b.HasOne("CLS.Budget.Domain.Entities.ForecastScenario", "ForecastScenario")
                        .WithMany("MonthlySnapshots")
                        .HasForeignKey("ForecastScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ForecastScenario");
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.ForecastScenarioCreditCard", b =>
                {
                    b.HasOne("CLS.Budget.Domain.Entities.ForecastScenario", "ForecastScenario")
                        .WithMany("CreditCards")
                        .HasForeignKey("ForecastScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ForecastScenario");
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.ImportedTransaction", b =>
                {
                    b.HasOne("CLS.Budget.Domain.Entities.AccountCategory", "AccountCategory")
                        .WithMany()
                        .HasForeignKey("AccountCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CLS.Budget.Domain.Entities.BudgetPaymentStatus", "BudgetPaymentStatus")
                        .WithMany()
                        .HasForeignKey("BudgetPaymentStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CLS.Budget.Domain.Entities.IncomeSource", "IncomeSource")
                        .WithMany()
                        .HasForeignKey("IncomeSourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CLS.Budget.Domain.Entities.TransactionImport", "TransactionImport")
                        .WithMany("Transactions")
                        .HasForeignKey("TransactionImportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountCategory");

                    b.Navigation("BudgetPaymentStatus");

                    b.Navigation("IncomeSource");

                    b.Navigation("TransactionImport");
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("CLS.Budget.Domain.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.PaySchedule", b =>
                {
                    b.HasOne("CLS.Budget.Domain.Entities.IncomeSource", "IncomeSource")
                        .WithMany()
                        .HasForeignKey("IncomeSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CLS.Budget.Domain.Entities.PayFrequencyType", "PayFrequencyType")
                        .WithMany()
                        .HasForeignKey("PayFrequencyTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IncomeSource");

                    b.Navigation("PayFrequencyType");
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.PayoffPlanEvent", b =>
                {
                    b.HasOne("CLS.Budget.Domain.Entities.ActivePayoffPlan", "ActivePayoffPlan")
                        .WithMany("Events")
                        .HasForeignKey("ActivePayoffPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActivePayoffPlan");
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.PayoffPlanPayment", b =>
                {
                    b.HasOne("CLS.Budget.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CLS.Budget.Domain.Entities.ActivePayoffPlan", "ActivePayoffPlan")
                        .WithMany("Payments")
                        .HasForeignKey("ActivePayoffPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CLS.Budget.Domain.Entities.PayoffPlanVersion", "PayoffPlanVersion")
                        .WithMany("Payments")
                        .HasForeignKey("PayoffPlanVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("ActivePayoffPlan");

                    b.Navigation("PayoffPlanVersion");
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.PayoffPlanVersion", b =>
                {
                    b.HasOne("CLS.Budget.Domain.Entities.ActivePayoffPlan", "ActivePayoffPlan")
                        .WithMany("Versions")
                        .HasForeignKey("ActivePayoffPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActivePayoffPlan");
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("CLS.Budget.Domain.Entities.AppUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.TransactionImport", b =>
                {
                    b.HasOne("CLS.Budget.Domain.Entities.IncomeSource", "IncomeSource")
                        .WithMany()
                        .HasForeignKey("IncomeSourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("IncomeSource");
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.Account", b =>
                {
                    b.Navigation("CreditCardDetail");
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.AccountCategory", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.ActivePayoffPlan", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Payments");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.BudgetModel", b =>
                {
                    b.Navigation("BudgetPayments");
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.ForecastScenario", b =>
                {
                    b.Navigation("CreditCards");

                    b.Navigation("MonthlySnapshots");
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.PayoffPlanVersion", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CLS.Budget.Domain.Entities.TransactionImport", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
