name: AWS Deploy React to S3

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend/cls-budget-web

    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci

      - name: Build React app
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          role-to-assume: arn:aws:iam::955598401326:role/YOUR_ROLE_NAME
          aws-region: us-east-1

      - name: Deploy to S3
        run: aws s3 sync dist s3://YOUR_BUCKET_NAME --delete
